### ISSUE TITLE
Invocazione WS ANPR - specifiche tecniche vb.net

### ISSUE THREAD

**Issue by GabriellaBallabio** [ncarandini/anpr-dotnet#2]
Buongiorno
stiamo relaizzato il client di connessione ai servizi esposti da ANPR per l'aggiornamento anagrafe da anagrafe locale.
Non risciamo a capire le modalità tecniche di comunicazione, esiste un client di test da utilizzare per verificare le modalità di creazione del pacchetto SOAP ?

Restiamo in attesa di gentile riscontro.
Saluti

**Comment by ncarandini** [comment]
Salve, mi spiace ma questo progetto non è attivo, nel senso che non è un progetto ufficiale ma solo un progetto personale (ancorché pubblico) che poi non ho portato avanti perché non mi serviva più.
